version: "3"
services:

  php-fpm:
    build:
      context: ${ENV_PATH}/php-fpm
    volumes:
      - ${APP_PATH}:/var/www
    expose:
      - "9000"
    networks:
      - backend

  mysql:
    build:
      context: ${ENV_PATH}/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  nginx:
    build:
      context: ${ENV_PATH}/nginx
    volumes:
      - ${APP_PATH}:/var/www
      - ${ENV_PATH}/nginx/logs:/var/log/nginx
      - ${ENV_PATH}/nginx/sites-available:/etc/nginx/sites-available
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
    links:
      - php-fpm

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
